display:
  inverted: false # If True, black background grey text
  maximalist: false # Bitcoin Maximalist mode. Only one currency with a news feed item from url b
  feedurl: https://bitcoinmagazine.com/.rss/full/
  quotesurl: https://www.reddit.com/r/quotes/top/.json?t=month&limit=100
  vcom: -2.61 # This is a number specific to your epd, ignore unless you know what it does
  coinnames: false # Include coinnames on display
  xshift: 0 # Pixels to shift image for fine tuning alignment
  yshift: 30 # Pixels to shift image for fine tuning alignment
  bold: false #Bolder Crypto display
ticker:
  currency: bitcoin, ethereum, cardano
  exchange: default # if you want price from a specific exchange specify here
  fiatcurrency: usd
  updatefrequency: 60 # Seconds (60 is the lower limit, to preserve epd)
  sparklinedays: 14 # Days of data on graph
  coinsperpage: 3  
headlines:
  feedurl: 'https://rss.nytimes.com/services/xml/rss/nyt/US.xml'
  feedname: "New York Times"
function: # Extra functionality
  mode: crypto,redditquotes, wordaday, newyorkercartoon, guardianheadlines, textfilequotes, stoic
  weight: 20, 1, 1, 1, 0, 0, 0 # Weighting for each of the above respectively
